'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, KeyRound, LockKeyhole, MailCheck, Sparkles } from 'lucide-react';
import { requestPasswordReset, signIn, signUp, updatePassword } from './actions';
import { ConvexAuthForm } from '@/components/auth/convex-auth-form';

function submit(action: (formData: FormData) => Promise<void>) {
    return async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        await action(new FormData(event.currentTarget));
    };
}

export function LoginForm() {
    return <div className="ff-card p-7 sm:p-9"><div className="mb-8"><span className="grid size-11 place-items-center rounded-2xl bg-[#f6dfb1]"><LockKeyhole className="size-5" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Welcome back.</h1><p className="mt-3 leading-6 text-muted-foreground">Pick up where your next video left off.</p></div><ConvexAuthForm mode="signIn" /><p className="mt-8 border-t border-border/70 pt-6 text-center text-sm text-muted-foreground">New to FinalFrame? <Link href="/signup" className="ff-link">Create an account</Link></p></div>;
    return <div className="ff-card p-7 sm:p-9"><div className="mb-8"><span className="grid size-11 place-items-center rounded-2xl bg-[#f6dfb1]"><LockKeyhole className="size-5" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Welcome back.</h1><p className="mt-3 leading-6 text-muted-foreground">Pick up where your next video left off.</p></div><form onSubmit={submit(signIn)} className="space-y-5"><div><label htmlFor="email" className="text-sm font-semibold">Email address</label><input type="email" id="email" name="email" required placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><div><div className="flex items-center justify-between gap-3"><label htmlFor="password" className="text-sm font-semibold">Password</label><Link href="/forgot-password" className="text-xs font-semibold text-accent underline underline-offset-4">Forgot password?</Link></div><input type="password" id="password" name="password" required placeholder="Your password" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><button type="submit" className="ff-button-primary w-full">Log in <ArrowRight className="size-4" /></button></form><p className="mt-8 border-t border-border/70 pt-6 text-center text-sm text-muted-foreground">New to FinalFrame? <Link href="/signup" className="ff-link">Create an account</Link></p></div>;
}

export function SignupForm() {
    return <div className="ff-card p-7 sm:p-9"><div className="mb-8"><span className="grid size-11 place-items-center rounded-2xl bg-[#f1c7b7]"><Sparkles className="size-5 text-accent" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Start with an idea.</h1><p className="mt-3 leading-6 text-muted-foreground">Create your studio, then make something worth watching.</p></div><ConvexAuthForm mode="signUp" /><p className="mt-8 border-t border-border/70 pt-6 text-center text-sm text-muted-foreground">Already have an account? <Link href="/login" className="ff-link">Log in</Link></p></div>;
    return <div className="ff-card p-7 sm:p-9"><div className="mb-8"><span className="grid size-11 place-items-center rounded-2xl bg-[#f1c7b7]"><Sparkles className="size-5 text-accent" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Start with an idea.</h1><p className="mt-3 leading-6 text-muted-foreground">Create your studio, then make something worth watching.</p></div><form onSubmit={submit(signUp)} className="space-y-5"><div><label htmlFor="fullName" className="text-sm font-semibold">Your name</label><input type="text" id="fullName" name="fullName" required placeholder="What should we call you?" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><div><label htmlFor="email" className="text-sm font-semibold">Email address</label><input type="email" id="email" name="email" required placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><div><label htmlFor="password" className="text-sm font-semibold">Create a password</label><input type="password" id="password" name="password" required minLength={8} placeholder="At least 8 characters" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /><p className="mt-2 text-xs text-muted-foreground">Use at least 8 characters.</p></div><button type="submit" className="ff-button-primary w-full">Create account <ArrowRight className="size-4" /></button></form><p className="mt-8 border-t border-border/70 pt-6 text-center text-sm text-muted-foreground">Already have an account? <Link href="/login" className="ff-link">Log in</Link></p></div>;
}

export function ForgotPasswordForm() {
    return <div className="ff-card p-7 sm:p-9"><span className="grid size-11 place-items-center rounded-2xl bg-[#c8ddd5]"><MailCheck className="size-5 text-[hsl(var(--success))]" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Find your way back in.</h1><p className="mt-3 leading-6 text-muted-foreground">Enter your email and we will send a password reset link.</p><form onSubmit={submit(requestPasswordReset)} className="mt-8 space-y-5"><div><label htmlFor="email" className="text-sm font-semibold">Email address</label><input type="email" id="email" name="email" required placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><button type="submit" className="ff-button-primary w-full">Send reset link</button></form><Link href="/login" className="ff-link mt-8 inline-flex items-center gap-2 text-sm"><ArrowLeft className="size-4" /> Back to log in</Link></div>;
}

export function ResetPasswordForm() {
    return <div className="ff-card p-7 sm:p-9"><span className="grid size-11 place-items-center rounded-2xl bg-[#f6dfb1]"><KeyRound className="size-5" /></span><h1 className="ff-display mt-7 text-3xl font-semibold">Choose a new password.</h1><p className="mt-3 leading-6 text-muted-foreground">A fresh password will keep your studio safe.</p><form onSubmit={submit(updatePassword)} className="mt-8 space-y-5"><div><label htmlFor="email" className="text-sm font-semibold">Account email</label><input type="email" id="email" name="email" required placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><div><label htmlFor="password" className="text-sm font-semibold">New password</label><input type="password" id="password" name="password" required minLength={8} placeholder="At least 8 characters" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><div><label htmlFor="confirmPassword" className="text-sm font-semibold">Confirm new password</label><input type="password" id="confirmPassword" name="confirmPassword" required minLength={8} placeholder="Type it again" className="mt-2 h-12 w-full rounded-xl border border-border bg-background px-4 text-sm outline-none transition focus:border-primary" /></div><button type="submit" className="ff-button-primary w-full">Update password <ArrowRight className="size-4" /></button></form><p className="mt-8 text-sm text-muted-foreground">Need to start over? <Link href="/login" className="ff-link">Back to log in</Link></p></div>;
}
