import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

const timestamp = v.number();
const json = v.any();

export default defineSchema({
  ...authTables,
  users: defineTable({
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.number()),
    phone: v.optional(v.string()),
    phoneVerificationTime: v.optional(v.number()),
    isAnonymous: v.optional(v.boolean()),
    externalId: v.optional(v.string()),
    authSubject: v.optional(v.string()),
    createdAt: v.optional(timestamp),
    updatedAt: v.optional(timestamp),
  }).index("by_external_id", ["externalId"]).index("by_auth_subject", ["authSubject"]).index("email", ["email"]),

  studios: defineTable({
    externalId: v.string(),
    ownerExternalId: v.string(),
    name: v.string(),
    credits: v.number(),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_external_id", ["externalId"]).index("by_owner", ["ownerExternalId"]),

  studioMembers: defineTable({
    studioExternalId: v.string(),
    userExternalId: v.string(),
    role: v.union(v.literal("owner"), v.literal("admin"), v.literal("member")),
    status: v.union(v.literal("active"), v.literal("invited"), v.literal("suspended")),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_studio", ["studioExternalId"]).index("by_user", ["userExternalId"]).index("by_studio_user", ["studioExternalId", "userExternalId"]),

  projects: defineTable({
    externalId: v.string(),
    studioExternalId: v.string(),
    name: v.string(),
    description: v.optional(v.string()),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_external_id", ["externalId"]).index("by_studio", ["studioExternalId"]),

  assets: defineTable({
    externalId: v.optional(v.string()),
    studioExternalId: v.string(),
    productionId: v.optional(v.id("productions")),
    source: v.string(),
    roles: v.array(v.string()),
    name: v.optional(v.string()),
    mimeType: v.optional(v.string()),
    storageUrl: v.optional(v.string()),
    storageId: v.optional(v.id("_storage")),
    checksum: v.optional(v.string()),
    provenance: v.optional(json),
    rights: v.optional(json),
    retention: v.optional(json),
    metadata: json,
    createdAt: timestamp,
  }).index("by_external_id", ["externalId"]).index("by_studio", ["studioExternalId"]).index("by_production", ["productionId"]),

  productions: defineTable({
    externalProjectId: v.string(),
    studioExternalId: v.string(),
    workflow: v.string(),
    inputMode: v.string(),
    requestedDurationSeconds: v.number(),
    language: v.string(),
    outputPreset: v.string(),
    status: v.string(),
    currentVersionId: v.optional(v.id("productionVersions")),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_project", ["externalProjectId"]).index("by_studio", ["studioExternalId"]),

  createIntents: defineTable({
    studioExternalId: v.string(),
    inputMode: v.string(),
    brief: v.string(),
    metadata: json,
    status: v.string(),
    productionId: v.optional(v.id("productions")),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_studio", ["studioExternalId"]).index("by_status", ["status"]),

  directorPlans: defineTable({
    productionId: v.id("productions"),
    input: json,
    plan: json,
    estimate: json,
    status: v.string(),
    createdAt: timestamp,
    approvedAt: v.optional(timestamp),
  }).index("by_production", ["productionId"]),

  productionVersions: defineTable({
    productionId: v.id("productions"),
    versionNumber: v.number(),
    status: v.string(),
    sourcePlanId: v.id("directorPlans"),
    approvedAt: v.optional(timestamp),
    createdAt: timestamp,
  }).index("by_production", ["productionId"]),

  productionBibles: defineTable({
    productionVersionId: v.id("productionVersions"),
    projectContext: json,
    characters: json,
    locations: json,
    products: json,
    style: json,
    story: json,
  }).index("by_version", ["productionVersionId"]),

  sequences: defineTable({
    productionVersionId: v.id("productionVersions"),
    title: v.string(),
    description: v.string(),
    orderIndex: v.number(),
  }).index("by_version", ["productionVersionId"]),

  scenes: defineTable({
    sequenceId: v.id("sequences"),
    title: v.string(),
    purpose: v.string(),
    visualDirection: v.string(),
    orderIndex: v.number(),
  }).index("by_sequence", ["sequenceId"]),

  shots: defineTable({
    sceneId: v.id("scenes"),
    title: v.string(),
    prompt: v.string(),
    durationSeconds: v.number(),
    orderIndex: v.number(),
    camera: json,
    requiredAssetIds: v.array(v.string()),
    status: v.string(),
  }).index("by_scene", ["sceneId"]),

  shotVersions: defineTable({
    shotId: v.id("shots"),
    versionNumber: v.number(),
    status: v.string(),
    assetId: v.optional(v.id("assets")),
    promptSnapshot: v.optional(v.string()),
    contextSnapshot: json,
  }).index("by_shot", ["shotId"]),

  generationJobs: defineTable({
    productionId: v.id("productions"),
    shotId: v.id("shots"),
    shotVersionId: v.id("shotVersions"),
    studioExternalId: v.string(),
    modality: v.string(),
    provider: v.string(),
    model: v.string(),
    request: json,
    response: v.optional(json),
    status: v.string(),
    progress: v.number(),
    estimatedCost: v.number(),
    idempotencyKey: v.string(),
    requestHash: v.optional(v.string()),
    reservationId: v.optional(v.id("creditReservations")),
    correlationId: v.optional(v.string()),
    leaseId: v.optional(v.string()),
    leaseExpiresAt: v.optional(timestamp),
    nextAttemptAt: v.optional(timestamp),
    actualCost: v.optional(v.number()),
    providerJobId: v.optional(v.string()),
    errorCode: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    attemptCount: v.number(),
    createdAt: timestamp,
    startedAt: v.optional(timestamp),
    completedAt: v.optional(timestamp),
    updatedAt: timestamp,
  }).index("by_idempotency", ["idempotencyKey"]).index("by_production", ["productionId"]).index("by_status", ["status"]),

  priceRules: defineTable({
    operation: v.string(),
    qualityTier: v.string(),
    unit: v.string(),
    creditsPerUnit: v.number(),
    enabled: v.boolean(),
  }).index("by_operation", ["operation", "qualityTier"]),

  creditReservations: defineTable({
    studioExternalId: v.string(),
    generationJobId: v.optional(v.id("generationJobs")),
    amount: v.number(),
    idempotencyKey: v.string(),
    status: v.string(),
    expiresAt: timestamp,
    createdAt: timestamp,
    committedAt: v.optional(timestamp),
    releasedAt: v.optional(timestamp),
    actualAmount: v.optional(v.number()),
  }).index("by_idempotency", ["idempotencyKey"]).index("by_studio", ["studioExternalId"]),

  creditTransactions: defineTable({
    studioExternalId: v.string(),
    delta: v.number(),
    transactionType: v.string(),
    source: v.string(),
    referenceId: v.optional(v.string()),
    metadata: json,
    createdAt: timestamp,
  }).index("by_studio", ["studioExternalId"]),

  assemblyJobs: defineTable({
    productionId: v.id("productions"),
    status: v.string(),
    manifest: json,
    outputUrl: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    rendererJobId: v.optional(v.string()),
    correlationId: v.optional(v.string()),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_production", ["productionId"]),

  paymentPurchases: defineTable({
    studioExternalId: v.string(),
    provider: v.string(),
    providerCheckoutId: v.optional(v.string()),
    amount: v.number(),
    currency: v.string(),
    credits: v.number(),
    reference: v.string(),
    status: v.string(),
    metadata: json,
    createdAt: timestamp,
    completedAt: v.optional(timestamp),
  }).index("by_reference", ["reference"]).index("by_checkout", ["providerCheckoutId"]).index("by_studio", ["studioExternalId"]),

  paymentEvents: defineTable({
    provider: v.string(),
    providerEventId: v.string(),
    eventType: v.string(),
    payload: json,
    processedAt: v.optional(timestamp),
    createdAt: timestamp,
  }).index("by_provider_event", ["provider", "providerEventId"]),

  creditEstimates: defineTable({
    studioExternalId: v.string(),
    productionId: v.optional(v.id("productions")),
    estimateVersion: v.string(),
    totalCredits: v.number(),
    lineItems: json,
    expiresAt: timestamp,
    createdAt: timestamp,
  }).index("by_production", ["productionId"]).index("by_studio", ["studioExternalId"]),

  reviews: defineTable({
    productionId: v.id("productions"),
    studioExternalId: v.string(),
    status: v.union(v.literal("DRAFT"), v.literal("REQUESTED"), v.literal("APPROVED"), v.literal("CHANGES_REQUESTED")),
    shareTokenHash: v.optional(v.string()),
    createdAt: timestamp,
    updatedAt: timestamp,
  }).index("by_production", ["productionId"]).index("by_studio", ["studioExternalId"]),

  reviewComments: defineTable({
    reviewId: v.id("reviews"),
    authorExternalId: v.optional(v.string()),
    body: v.string(),
    timeSeconds: v.optional(v.number()),
    resolvedAt: v.optional(timestamp),
    createdAt: timestamp,
  }).index("by_review", ["reviewId"]),

  exports: defineTable({
    productionId: v.id("productions"),
    studioExternalId: v.string(),
    assemblyJobId: v.optional(v.id("assemblyJobs")),
    preset: v.string(),
    status: v.string(),
    storageId: v.optional(v.id("_storage")),
    outputUrl: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    createdAt: timestamp,
    completedAt: v.optional(timestamp),
  }).index("by_production", ["productionId"]).index("by_studio", ["studioExternalId"]),

  auditEvents: defineTable({
    studioExternalId: v.optional(v.string()),
    actorExternalId: v.optional(v.string()),
    action: v.string(),
    entityType: v.string(),
    entityId: v.string(),
    correlationId: v.optional(v.string()),
    metadata: json,
    createdAt: timestamp,
  }).index("by_studio", ["studioExternalId"]).index("by_entity", ["entityType", "entityId"]),
});
