import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, HelpCircle, Mail, MessageCircle } from 'lucide-react';
import { SectionHeading } from '@/components/finalframe/section-heading';

export default function ContactPage() {
  return <div>
    <section className="ff-section bg-[#f4ead6]"><div className="ff-container grid gap-12 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="ff-eyebrow">Contact FinalFrame</p><h1 className="public-heading-hero mt-5 max-w-4xl">Bring us the question behind the video.</h1></div><p className="public-body-text max-w-md lg:justify-self-end">Need help choosing a workflow, bringing a team on board, or figuring out where to start? We can help.</p></div></section>
    <section className="ff-section"><div className="ff-container grid gap-5 md:grid-cols-3">{[[HelpCircle,'Product help','Questions about making a project, credits, media, or review.'],[BriefcaseBusiness,'Business and teams','Talk through repeat production, client work, and collaboration.'],[MessageCircle,'A creative question','Share the idea you are trying to make and we will point you in the right direction.']].map(([Icon, title, text]) => <div key={title as string} className="ff-card p-7"><div className="grid size-11 place-items-center rounded-2xl bg-secondary"><Icon className="size-5" /></div><h2 className="ff-display mt-12 text-2xl font-semibold">{title as string}</h2><p className="mt-3 leading-7 text-muted-foreground">{text as string}</p><a href="mailto:hello@finalframe.ai" className="ff-link mt-7 inline-flex items-center gap-2 text-sm">Send a note <ArrowRight className="size-4" /></a></div>)}</div></section>
    <section className="ff-section border-y border-border/70 bg-secondary/35"><div className="ff-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="A simple route in" title="You can always start with a message." description="Tell us what you want to make, where you are stuck, or what you are trying to understand. A real person will help you find the next step." /><div className="ff-card p-7 sm:p-9"><div className="flex items-center gap-3 border-b border-border/70 pb-5"><span className="grid size-10 place-items-center rounded-xl bg-[#f1c7b7]"><Mail className="size-5 text-accent" /></span><div><p className="font-semibold">hello@finalframe.ai</p><p className="text-sm text-muted-foreground">For product, support, and partnership questions</p></div></div><p className="mt-7 text-sm leading-7 text-muted-foreground">If you already have an account, the fastest path is to use the in-app help link so we can see the right project context.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signup" className="ff-button-primary">Start creating <ArrowRight className="size-4" /></Link><Link href="/about" className="ff-button-quiet">Learn about FinalFrame</Link></div></div></div></section>
  </div>;
}
