export const validCreateIntent = {
  preset: 'ANIMATED_COMEDY_2D',
  inputMode: 'IDEA',
  brief: 'Two original characters argue over a missing delivery, then discover the parcel is behind them.',
  inputAssetIds: [],
  language: 'en',
  platform: 'shorts',
  aspectRatio: '9:16',
  durationSeconds: 18,
  qualityTier: 'STANDARD',
} as const;

export const validDirectorPlan = {
  intentSummary: 'A short, visual comedy beat with a clear discovery ending.',
  preset: 'ANIMATED_COMEDY_2D',
  inputMode: 'IDEA',
  language: 'en',
  platform: 'shorts',
  durationSeconds: 18,
  aspectRatio: '9:16',
  script: 'Mina blames Jo for losing the parcel. Jo points behind Mina. They both turn and freeze.',
  speakers: [
    {
      id: 'speaker-mina-1',
      speakerLabel: 'Mina',
      characterId: 'character-mina',
      startSeconds: 0,
      endSeconds: 7,
      text: 'Where did the parcel go?',
      confidence: 0.99,
      reviewed: true,
    },
    {
      id: 'speaker-jo-1',
      speakerLabel: 'Jo',
      characterId: 'character-jo',
      startSeconds: 7,
      endSeconds: 12,
      text: 'It is right behind you.',
      confidence: 0.98,
      reviewed: true,
    },
  ],
  shots: [
    {
      sequenceId: 'sequence-1',
      sceneId: 'scene-1',
      orderIndex: 0,
      purpose: 'Establish the search and Mina’s misplaced confidence.',
      durationSeconds: 7,
      dialogueSegmentIds: ['speaker-mina-1'],
      characterIds: ['character-mina', 'character-jo'],
      locationIds: ['location-shopfront'],
      productIds: [],
      referencePackIds: ['pack-cast-v1', 'pack-location-v1'],
      camera: { framing: 'medium two-shot', movement: 'slow push-in', lens: 'standard' },
      action: 'Mina checks an empty shelf while Jo watches the parcel remain visible behind her.',
      prompt: 'Original 2D animated characters Mina and Jo in a busy neighborhood shopfront; Mina searches an empty shelf while a sealed parcel is clearly visible behind her; warm afternoon light; medium two-shot; clean readable silhouettes; no text or logos.',
      negativePrompt: 'No extra characters, no brand logos, no deformed hands, no unreadable text.',
      providerCapability: 'VIDEO_GENERATION',
    },
    {
      sequenceId: 'sequence-1',
      sceneId: 'scene-1',
      orderIndex: 1,
      purpose: 'Deliver the reveal and reaction payoff.',
      durationSeconds: 11,
      dialogueSegmentIds: ['speaker-jo-1'],
      characterIds: ['character-mina', 'character-jo'],
      locationIds: ['location-shopfront'],
      productIds: [],
      referencePackIds: ['pack-cast-v1', 'pack-location-v1'],
      camera: { framing: 'wide reveal', movement: 'quick pan right', lens: 'wide' },
      action: 'Jo points behind Mina; Mina turns, sees the parcel, and freezes before both characters laugh.',
      prompt: 'Original 2D animated reveal in the same neighborhood shopfront; Jo points behind Mina, Mina turns toward the sealed parcel, then both characters freeze and laugh; preserve the same character designs, wardrobe, palette, and afternoon lighting; wide reveal with a quick pan right.',
      negativePrompt: 'No new characters, no location change, no logo substitution, no text artifacts.',
      providerCapability: 'VIDEO_GENERATION',
    },
  ],
  creativeGuide: {
    visualStyle: 'Warm hand-drawn 2D comedy with bold silhouettes and readable reaction poses.',
    palette: ['#F4C95D', '#D96C4F', '#20323A'],
    continuityRules: ['Mina wears the yellow shirt in every shot.', 'The parcel stays behind Mina until the reveal.'],
    audioDirection: 'Dry dialogue with a short comedic pause before the reaction.',
  },
  riskFlags: [],
  estimatedCredits: 12,
  planVersion: 1,
  approvalStatus: 'DRAFT',
  currentStage: 'PLAN',
  qualityGateStatus: 'NOT_RUN',
  qualityGates: [],
} as const;

export const genericShot = {
  sequenceId: 'sequence-generic',
  sceneId: 'scene-generic',
  orderIndex: 0,
  purpose: 'Show the scene.',
  durationSeconds: 4,
  dialogueSegmentIds: [],
  characterIds: [],
  locationIds: [],
  productIds: [],
  referencePackIds: [],
  camera: { framing: 'medium shot', movement: 'static', lens: 'standard' },
  action: 'Things happen.',
  prompt: 'A cinematic scene with nice lighting and interesting visuals.',
  negativePrompt: null,
  providerCapability: 'VIDEO_GENERATION',
} as const;
