import Link from 'next/link';
import { ArrowRight, Check, Eye, FileText, MessageCircle, Play, Sparkles, WalletCards } from 'lucide-react';
import { SectionHeading } from '@/components/finalframe/section-heading';
import { workflowSteps } from '@/lib/ui/labels';

const icons = [Sparkles, FileText, WalletCards, Play, MessageCircle, Check];

export default function MethodologyPage() {
  return <div>
    <section className="ff-section bg-[#f4ead6]"><div className="ff-container"><p className="ff-eyebrow">How it works</p><h1 className="public-heading-hero mt-5 max-w-4xl">A simple path from “I have an idea” to “send me the link.”</h1><p className="public-body-text mt-7 max-w-2xl">FinalFrame does the production planning underneath. You get clear choices, a visible plan, and a chance to approve before the expensive part starts.</p></div></section>
    <section className="ff-section"><div className="ff-container"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{workflowSteps.map((step, index) => { const Icon = icons[index]; return <article key={step.key} className={`ff-card p-7 ${index === 1 ? 'lg:mt-12' : index === 4 ? 'lg:-mt-8' : ''}`}><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-secondary text-foreground"><Icon className="size-5" /></span><span className="ff-eyebrow">0{index + 1}</span></div><h2 className="ff-display mt-14 text-2xl font-semibold">{step.label}</h2><p className="mt-3 leading-7 text-muted-foreground">{step.description}</p></article>; })}</div></div></section>
    <section className="ff-section border-y border-border/70 bg-secondary/35"><div className="ff-container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionHeading eyebrow="You stay in the loop" title="The studio never asks you to trust a mystery button." description="Every project has a clear next step. If something needs your attention, FinalFrame tells you why and what you can do." /><div className="ff-card overflow-hidden p-5"><div className="flex items-center gap-3 border-b border-border/70 pb-5"><span className="grid size-9 place-items-center rounded-xl bg-[#f6dfb1]"><Eye className="size-4" /></span><div><p className="text-sm font-semibold">Your video plan</p><p className="text-xs text-muted-foreground">Ready for your review</p></div></div><div className="mt-5 space-y-3">{['Story and message', 'Visual style and references', 'Estimated credits', 'What happens next'].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl bg-secondary/60 p-4"><span className={`grid size-7 place-items-center rounded-full text-xs font-semibold ${index < 2 ? 'bg-[#c8ddd5] text-[hsl(var(--success))]' : 'bg-[#f1c7b7] text-accent'}`}>{index < 2 ? <Check className="size-3.5" /> : index + 1}</span><span className="text-sm font-medium">{item}</span></div>)}</div></div></div></section>
    <section className="ff-section"><div className="ff-container text-center"><SectionHeading eyebrow="Start where you are" title="A rough note is enough." description="You can make the plan more specific as you go. Your first message does not need to sound like a professional brief." align="center" /><Link href="/signup" className="ff-button-primary mt-8">Start creating <ArrowRight className="size-4" /></Link></div></section>
  </div>;
}
