import { CheckCircle2, CircleAlert, Clock3, ReceiptText, ScrollText } from 'lucide-react';

type OperationData = {
  jobs: Array<{ id: string; status: string; provider: string; model: string; createdAt: number; updatedAt: number; errorMessage?: string }>;
  payments: Array<{ id: string; status: string; provider: string; amount: number; currency: string; credits: number; createdAt: number }>;
  reservations: Array<{ id: string; status: string; amount: number; createdAt: number; expiresAt: number }>;
  audit: Array<{ id: string; action: string; entityType: string; entityId: string; createdAt: number }>;
};

const date = (value: number) => new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export function OperationsTable({ data, kind }: { data: OperationData; kind: 'jobs' | 'payments' | 'credits' | 'audit' }) {
  if (kind === 'jobs') return <section className="studio-card overflow-hidden"><div className="border-b border-[#6c5746]/45 p-6"><div className="flex items-center gap-3"><Clock3 className="size-5 text-[#f6dfb1]" /><div><h2 className="font-semibold">Generation jobs</h2><p className="mt-1 text-sm text-[#cbb7a4]">Live job records from Convex.</p></div></div></div>{data.jobs.length ? <div className="divide-y divide-[#6c5746]/30">{data.jobs.map((job) => <div key={String(job.id)} className="grid gap-2 px-6 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-sm font-semibold">{job.provider} · {job.model}</p><p className="mt-1 text-xs text-[#cbb7a4]">Created {date(job.createdAt)}</p>{job.errorMessage && <p className="mt-2 text-sm text-[#f1c7b7]">{job.errorMessage}</p>}</div><span className={`inline-flex w-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${job.status === 'FAILED' ? 'bg-[#f1c7b7] text-[#211b18]' : job.status === 'COMPLETED' ? 'bg-[#c8ddd5] text-[#211b18]' : 'bg-[#f6dfb1] text-[#211b18]'}`}>{job.status === 'FAILED' ? <CircleAlert className="size-3" /> : <CheckCircle2 className="size-3" />}{job.status}</span></div>)}</div> : <EmptyOperations label="No generation jobs yet." />}</section>;
  if (kind === 'payments') return <section className="studio-card overflow-hidden"><div className="border-b border-[#6c5746]/45 p-6"><div className="flex items-center gap-3"><ReceiptText className="size-5 text-[#f6dfb1]" /><div><h2 className="font-semibold">Payment events</h2><p className="mt-1 text-sm text-[#cbb7a4]">Purchases will appear here when payments are enabled.</p></div></div></div>{data.payments.length ? <div className="divide-y divide-[#6c5746]/30">{data.payments.map((payment) => <div key={String(payment.id)} className="flex flex-wrap items-center justify-between gap-3 px-6 py-5"><div><p className="text-sm font-semibold">{payment.provider} · {payment.currency} {payment.amount.toFixed(2)}</p><p className="mt-1 text-xs text-[#cbb7a4]">{payment.credits} credits · {date(payment.createdAt)}</p></div><span className="rounded-full bg-[#f6dfb1] px-3 py-1.5 text-xs font-semibold text-[#211b18]">{payment.status}</span></div>)}</div> : <EmptyOperations label="No payment events are available." />}</section>;
  if (kind === 'credits') return <section className="studio-card overflow-hidden"><div className="border-b border-[#6c5746]/45 p-6"><div className="flex items-center gap-3"><Clock3 className="size-5 text-[#f6dfb1]" /><div><h2 className="font-semibold">Credit reservations</h2><p className="mt-1 text-sm text-[#cbb7a4]">Reservations are shown read-only until accounting is enabled.</p></div></div></div>{data.reservations.length ? <div className="divide-y divide-[#6c5746]/30">{data.reservations.map((reservation) => <div key={String(reservation.id)} className="flex flex-wrap items-center justify-between gap-3 px-6 py-5"><div><p className="text-sm font-semibold">{reservation.amount} credits</p><p className="mt-1 text-xs text-[#cbb7a4]">Created {date(reservation.createdAt)} · expires {date(reservation.expiresAt)}</p></div><span className="rounded-full bg-[#f6dfb1] px-3 py-1.5 text-xs font-semibold text-[#211b18]">{reservation.status}</span></div>)}</div> : <EmptyOperations label="No credit reservations are available." />}</section>;
  return <section className="studio-card overflow-hidden"><div className="border-b border-[#6c5746]/45 p-6"><div className="flex items-center gap-3"><ScrollText className="size-5 text-[#f6dfb1]" /><div><h2 className="font-semibold">Audit trail</h2><p className="mt-1 text-sm text-[#cbb7a4]">Administrative and system events from Convex.</p></div></div></div>{data.audit.length ? <div className="divide-y divide-[#6c5746]/30">{data.audit.map((event) => <div key={String(event.id)} className="px-6 py-5"><p className="text-sm font-semibold">{event.action}</p><p className="mt-1 text-xs text-[#cbb7a4]">{event.entityType} · {event.entityId} · {date(event.createdAt)}</p></div>)}</div> : <EmptyOperations label="No audit events are available." />}</section>;
}

function EmptyOperations({ label }: { label: string }) {
  return <div className="flex min-h-40 items-center justify-center px-6 text-center text-sm text-[#cbb7a4]"><span>{label}</span></div>;
}
