import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, Play } from 'lucide-react';
import { showcaseItems } from '@/content/marketing';
import { SectionHeading } from '@/components/finalframe/section-heading';

export default function CaseStudiesPage() {
  return <div>
    <section className="ff-section bg-[#f4ead6]"><div className="ff-container"><p className="ff-eyebrow">What you can make</p><h1 className="public-heading-hero mt-5 max-w-4xl">The format depends on the job. The starting point can still be simple.</h1><p className="public-body-text mt-7 max-w-2xl">These are examples of the kinds of stories FinalFrame is designed to help you make. They are creative directions, not invented customer results.</p></div></section>
    <section className="ff-section"><div className="ff-container space-y-8">{showcaseItems.map((item, index) => <article key={item.title} className={`grid gap-8 rounded-[1.5rem] bg-secondary/50 p-5 sm:p-8 lg:grid-cols-2 lg:items-center ${index % 2 ? 'lg:[&>div:first-child]:order-2' : ''}`}><div className="relative aspect-[1.35] overflow-hidden rounded-[1.1rem] bg-[#2c2520]"><Image src={item.image} alt={item.title} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /><span className="absolute left-4 top-4 inline-flex items-center gap-2 rounded-full bg-[#211b18]/80 px-3 py-2 text-xs font-semibold text-[#f7f0e3]"><Play className="size-3.5" /> Preview direction</span></div><div className="p-2 sm:p-5"><p className="ff-eyebrow">{item.type}</p><h2 className="ff-display mt-4 text-4xl font-semibold">{item.title}</h2><p className="mt-5 max-w-lg text-base leading-7 text-muted-foreground">{item.description} Start with the purpose, then let the plan find the right rhythm, voice, visuals, and format.</p><div className="mt-7 space-y-3 text-sm text-muted-foreground"><p className="flex items-center gap-3"><Check className="size-4 text-[hsl(var(--success))]" /> Choose a platform and length</p><p className="flex items-center gap-3"><Check className="size-4 text-[hsl(var(--success))]" /> Add your own references when you have them</p><p className="flex items-center gap-3"><Check className="size-4 text-[hsl(var(--success))]" /> Review the plan before making it</p></div></div></article>)}</div></section>
    <section className="ff-section border-y border-border/70 bg-[#211b18] text-[#f7f0e3]"><div className="ff-container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><SectionHeading eyebrow="Your story can be specific" title="Local, funny, useful, emotional, direct." description="FinalFrame is not trying to make every video look the same. It gives you a clear path to the video that fits your audience." /><Link href="/signup" className="ff-button-primary lg:justify-self-end">Make your own example <ArrowRight className="size-4" /></Link></div></section>
  </div>;
}
