import Link from 'next/link';
import { ArrowRight, Check, Compass, HeartHandshake, Layers3, Sparkles } from 'lucide-react';
import { SectionHeading } from '@/components/finalframe/section-heading';

export default function AboutPage() {
  return <div>
    <section className="ff-section bg-[#f4ead6]"><div className="ff-container grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="ff-eyebrow">About FinalFrame</p><h1 className="public-heading-hero mt-5 max-w-4xl">Good video starts with a clear idea, not a complicated tool.</h1></div><p className="public-body-text max-w-md lg:justify-self-end">We are building a production studio for people who need to make things, not study production software.</p></div></section>
    <section className="ff-section"><div className="ff-container grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><SectionHeading eyebrow="Why we are here" title="There are more good ideas than there are easy ways to make them." description="A founder has a product to explain. A small team has a launch to share. A creator has a story in mind. FinalFrame gives each of them a path from thought to video." /><div className="space-y-5"><div className="ff-card p-7"><Compass className="size-6 text-accent" /><h3 className="ff-display mt-12 text-2xl font-semibold">A guide, not a black box</h3><p className="mt-3 leading-7 text-muted-foreground">You see the plan, the choices, and the cost before the heavy work begins.</p></div><div className="ff-card bg-[#211b18] p-7 text-[#f7f0e3]"><Layers3 className="size-6 text-[#f6dfb1]" /><h3 className="ff-display mt-12 text-2xl font-semibold">A studio, not a prompt box</h3><p className="mt-3 leading-7 text-[#cbb7a4]">Your idea has parts, versions, media, and a review path so the finished video feels intentional.</p></div></div></div></section>
    <section className="ff-section border-y border-border/70 bg-secondary/35"><div className="ff-container"><SectionHeading eyebrow="What we believe" title="Make the complicated parts invisible, not the creative choices." /><div className="mt-12 grid gap-4 md:grid-cols-3">{[['Start human','Use your own words, even if they are rough.'],['Show the work','A clear plan builds trust before generation.'],['Keep it yours','Your media, story, and decisions stay at the center.']].map(([title, text]) => <div key={title} className="rounded-[1.25rem] bg-background p-7"><Check className="size-5 text-[hsl(var(--success))]" /><h3 className="ff-display mt-10 text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="ff-section"><div className="ff-container grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="rounded-[2rem] bg-[#f1c7b7] p-8 sm:p-12"><div className="rounded-[1.25rem] bg-card p-6 shadow-xl"><p className="ff-eyebrow">The FinalFrame promise</p><p className="ff-display mt-8 text-3xl font-semibold leading-tight">Describe it. Paste it. Upload it. Bring your own assets. Approve the cost. Get the video.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold"><HeartHandshake className="size-5 text-accent" /> A calmer way to create</div></div></div><div><SectionHeading eyebrow="Built for the way people work now" title="From the first sentence to the final share link." description="FinalFrame is made for the person who knows what they want to say, even if they have never opened a timeline editor." /><Link href="/signup" className="ff-button-primary mt-8">Make your first video <ArrowRight className="size-4" /></Link></div></div></section>
    <section className="ff-container pb-24 sm:pb-32"><div className="rounded-[2rem] bg-foreground p-8 text-background sm:p-14"><Sparkles className="size-6 text-primary" /><h2 className="ff-display mt-8 max-w-2xl text-4xl font-semibold sm:text-5xl">The studio is growing around your ideas.</h2><p className="mt-5 max-w-xl leading-7 text-background/70">Start with one short video. Bring the next idea when you are ready.</p><Link href="/contact" className="ff-button-primary mt-8">Talk to the team <ArrowRight className="size-4" /></Link></div></section>
  </div>;
}
