import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Check, CirclePlay, FileText, ImagePlus, Mic2, MousePointer2, Sparkles, Upload, WandSparkles } from 'lucide-react';
import { SectionHeading } from '@/components/finalframe/section-heading';
import { StoryboardDemo } from '@/components/finalframe/storyboard-demo';
import { creationModes } from '@/lib/ui/labels';
import { faqs, showcaseItems } from '@/content/marketing';

export default function HomePage() {
  return (
    <div className="overflow-hidden">
      <section className="ff-noise relative border-b border-border/70 bg-[#f4ead6]">
        <div className="ff-container grid min-h-[680px] items-center gap-16 py-20 lg:grid-cols-[.92fr_1.08fr] lg:py-28">
          <div className="relative z-10">
            <p className="ff-eyebrow flex items-center gap-2"><span className="size-2 rounded-full bg-accent" /> A creative studio for real people</p>
            <h1 className="public-heading-hero mt-6 max-w-3xl">Make the video in your head.</h1>
            <p className="public-body-text mt-7 max-w-xl">Describe an idea, paste a script, upload footage, or bring your own media. FinalFrame helps you shape it, see the cost, and make a video you are proud to share.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/signup" className="ff-button-primary min-h-12 px-6">Start with an idea <ArrowRight className="size-4" /></Link><Link href="/methodology" className="ff-button-quiet min-h-12 px-5"><CirclePlay className="size-4" /> See how it works</Link></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Check className="size-4 text-[hsl(var(--success))]" /> See your plan first</span><span className="flex items-center gap-2"><Check className="size-4 text-[hsl(var(--success))]" /> Approve the cost</span><span className="flex items-center gap-2"><Check className="size-4 text-[hsl(var(--success))]" /> Keep your media yours</span></div>
          </div>
          <div className="relative lg:-mr-24">
            <div className="absolute -left-8 -top-8 size-28 rounded-full bg-[#e8b37d]/45 blur-2xl" />
            <div className="relative rounded-[2rem] border border-[#6a4a32]/15 bg-[#e1caa5]/60 p-3 shadow-[0_35px_80px_-45px_rgba(54,35,20,.75)] sm:p-5">
              <div className="grid grid-cols-[.27fr_1fr] gap-3 rounded-[1.4rem] bg-[#211b18] p-3 text-[#f7f0e3] sm:p-4">
                <div className="space-y-2 rounded-[.9rem] bg-[#2a231f] p-2"><div className="mb-4 flex items-center gap-2 px-1"><span className="size-5 rounded-md bg-[#f6dfb1]" /><span className="text-[9px] font-semibold">FinalFrame</span></div>{['Idea', 'Plan', 'Make', 'Review'].map((step, index) => <div key={step} className={`rounded-lg px-2 py-3 text-[10px] ${index === 1 ? 'bg-[#f6dfb1] font-semibold text-[#211b18]' : 'text-[#ad9d8e]'}`}>{step}</div>)}</div>
                <div className="space-y-3"><div className="flex items-center justify-between rounded-xl bg-[#342b25] px-4 py-3"><span className="text-xs font-semibold">A short story about a brave pigeon</span><span className="rounded-full bg-[#f6dfb1] px-2 py-1 text-[9px] font-semibold text-[#211b18]">Plan ready</span></div><div className="relative aspect-[1.25] overflow-hidden rounded-xl bg-[#b9734b]"><Image src="/images/gallery/frame_1.png" alt="Storyboard preview of a colorful cartoon scene" fill className="object-cover" sizes="(max-width: 1024px) 90vw, 45vw" /><div className="absolute bottom-3 left-3 rounded-lg bg-[#211b18]/80 px-3 py-2 text-[10px]">Part 2 · The surprise</div></div><div className="grid grid-cols-3 gap-2">{['/images/gallery/frame_2.png','/images/gallery/frame_3.png','/images/gallery/frame_4.png'].map((src, index) => <div key={src} className={`relative aspect-video overflow-hidden rounded-lg ${index === 0 ? 'ring-2 ring-[#f6dfb1]' : ''}`}><Image src={src} alt={`Storyboard thumbnail ${index + 1}`} fill className="object-cover" sizes="15vw" /></div>)}</div></div>
              </div>
            </div>
            <div className="absolute -bottom-5 -left-5 flex items-center gap-3 rounded-2xl border border-border/70 bg-card px-4 py-3 shadow-xl sm:-left-12"><span className="grid size-9 place-items-center rounded-xl bg-[#c8ddd5] text-[hsl(var(--success))]"><WandSparkles className="size-4" /></span><div><p className="text-xs font-semibold text-foreground">Made for first-timers</p><p className="mt-1 text-[11px] text-muted-foreground">No prompt lessons required</p></div></div>
          </div>
        </div>
      </section>

      <section className="ff-section"><div className="ff-container"><SectionHeading eyebrow="A better starting point" title="You do not need a production team to make something good." description="FinalFrame gives your rough idea a little structure, keeps the important details consistent, and lets you stay in control without making you learn a new language." /><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{creationModes.map((mode, index) => <Link href="/signup" key={mode.id} className={`group ${mode.accent} rounded-[1.25rem] p-6 transition duration-300 hover:-translate-y-2 ${index === 1 ? 'lg:mt-10' : index === 3 ? 'lg:mt-5' : ''}`}><span className="grid size-10 place-items-center rounded-xl bg-white/55 text-foreground">{index === 0 ? <Sparkles className="size-5" /> : index === 1 ? <FileText className="size-5" /> : index === 2 ? <Upload className="size-5" /> : <ImagePlus className="size-5" />}</span><h3 className="ff-display mt-12 text-2xl font-semibold">{mode.title}</h3><p className="mt-3 text-sm leading-6 text-foreground/70">{mode.description}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">Try it <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="ff-section border-y border-border/70 bg-secondary/30"><div className="ff-container"><SectionHeading eyebrow="See the difference" title="Your idea becomes a story you can actually follow." description="FinalFrame shows the plan before it spends credits. You can change the parts that matter, then let the studio handle the heavy lifting." /><div className="mt-14"><StoryboardDemo /></div></div></section>

      <section className="ff-section"><div className="ff-container"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><SectionHeading eyebrow="What people make" title="From a funny cartoon to the video on your homepage." description="Start with the job you need the video to do. The creative style can come after." /><Link href="/case-studies" className="ff-link inline-flex items-center gap-2 text-sm lg:justify-self-end">Explore examples <ArrowRight className="size-4" /></Link></div><div className="mt-14 grid gap-5 md:grid-cols-2">{showcaseItems.map((item, index) => <article key={item.title} className={`group relative overflow-hidden rounded-[1.25rem] bg-[#2c2520] ${index === 0 ? 'md:row-span-2' : ''}`}><div className={`${index === 0 ? 'aspect-[.88]' : 'aspect-[1.45]'} relative`}><Image src={item.image} alt={item.title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 50vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#211b18] via-transparent to-transparent" /><div className="absolute bottom-0 left-0 right-0 p-6 text-[#f7f0e3]"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#f6dfb1]">{item.type}</p><h3 className="ff-display mt-2 text-2xl font-semibold">{item.title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#e0d4c7]/80">{item.description}</p></div></div></article>)}</div></div></section>

      <section className="ff-section bg-[#211b18] text-[#f7f0e3]"><div className="ff-container"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="ff-eyebrow text-[#cbb7a4]">How it works</p><h2 className="public-heading-section mt-4 text-[#f7f0e3]">A calm path from thought to finished video.</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#cbb7a4]">You always know what is happening, what it costs, and what you can change.</p></div><div className="grid gap-3 sm:grid-cols-2">{[['01','Describe it','Tell us what you want to say or show.'],['02','Build the plan','Review the story, style, and media.'],['03','Approve the cost','See the estimate before generation.'],['04','Get the video','Review, revise, and download.']].map(([number, title, description]) => <div key={number} className="rounded-[1.1rem] border border-[#6c5746]/45 bg-[#2a231f] p-6"><span className="text-sm font-semibold text-[#f6dfb1]">{number}</span><h3 className="ff-display mt-12 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#cbb7a4]">{description}</p></div>)}</div></div></div></section>

      <section className="ff-section"><div className="ff-container grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><SectionHeading eyebrow="Bring your own world" title="Your logo, your footage, your characters, your voice." description="Upload what makes the video yours. FinalFrame keeps those references attached to the project so the story stays consistent from the first part to the last." /><div className="mt-9 grid gap-3 sm:grid-cols-2">{[['Your media stays attached','Keep products, characters, and references easy to find.'],['Continuity you can see','Know which image, voice, or clip belongs to each part.'],['Room to change your mind','Make a new version without losing the old one.'],['A review link for others','Share a clean version and collect notes.']].map(([title, description]) => <div key={title} className="ff-soft-card p-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>)}</div></div><div className="relative rounded-[2rem] bg-[#f1c7b7] p-6 sm:p-10"><div className="rounded-[1.25rem] bg-card p-5 shadow-xl sm:p-7"><div className="flex items-center justify-between border-b border-border/70 pb-5"><div><p className="ff-eyebrow">Your media</p><p className="mt-2 text-lg font-semibold">A little library for your story</p></div><ImagePlus className="size-5 text-accent" /></div><div className="mt-5 grid grid-cols-3 gap-3">{['/images/templates/brand_story.png','/images/templates/avatar_keynote.png','/images/templates/viral_ad.png'].map((src) => <div key={src} className="relative aspect-square overflow-hidden rounded-xl"><Image src={src} alt="FinalFrame media reference" fill className="object-cover" sizes="20vw" /></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-xl bg-secondary p-3 text-sm"><span className="grid size-8 place-items-center rounded-lg bg-[#c8ddd5]"><Mic2 className="size-4 text-[hsl(var(--success))]" /></span>Voice and audio can join the story too</div></div></div></div></section>

      <section className="ff-section border-y border-border/70 bg-[#f4ead6]"><div className="ff-container grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><SectionHeading eyebrow="Clear before costly" title="No surprise button at the end." description="Before FinalFrame starts an expensive step, you see the plan, the estimated credits, and the parts that will be created. Approve when it looks right." /><div className="ff-card p-6 sm:p-8"><div className="flex items-center justify-between border-b border-border/70 pb-5"><div><p className="ff-eyebrow">Estimated video</p><p className="mt-2 text-2xl font-semibold">30-second product story</p></div><span className="rounded-full bg-[#f6dfb1] px-3 py-2 text-sm font-semibold">Ready to review</span></div><div className="mt-6 space-y-4">{[['4','Story parts'],['8','Video takes'],['1','Review version']].map(([value, label]) => <div key={label} className="flex items-center justify-between rounded-xl bg-secondary/60 px-4 py-4"><span className="text-sm text-muted-foreground">{label}</span><span className="font-semibold">{value}</span></div>)}</div><div className="mt-6 flex items-end justify-between border-t border-border/70 pt-6"><div><p className="text-sm text-muted-foreground">Estimated cost</p><p className="mt-1 text-3xl font-semibold">48 credits</p></div><MousePointer2 className="size-5 text-accent" /></div></div></div></section>

      <section className="ff-section"><div className="ff-container"><SectionHeading eyebrow="Questions, answered" title="You can start without knowing the right words." align="center" /><div className="mx-auto mt-12 max-w-3xl divide-y divide-border/70 border-y border-border/70">{faqs.map((faq) => <details key={faq.question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-left font-semibold"><span>{faq.question}</span><span className="text-2xl font-normal text-muted-foreground transition group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl leading-7 text-muted-foreground">{faq.answer}</p></details>)}</div></div></section>

      <section className="ff-container pb-24 sm:pb-32"><div className="relative overflow-hidden rounded-[2rem] bg-foreground px-7 py-16 text-background sm:px-14 sm:py-20"><div className="absolute -right-12 -top-24 size-72 rounded-full bg-primary/25 blur-3xl" /><div className="relative max-w-2xl"><p className="ff-eyebrow text-background/60">Your next video can start here</p><h2 className="ff-display mt-4 text-4xl font-semibold leading-tight sm:text-6xl">Bring the rough idea. Leave with something real.</h2><p className="mt-6 max-w-xl text-base leading-7 text-background/70">Start free, explore the plan, and decide what is worth making.</p><Link href="/signup" className="ff-button-primary mt-8 min-h-12 bg-primary px-6">Make a video <ArrowRight className="size-4" /></Link></div></div></section>
    </div>
  );
}
