import Link from 'next/link';
import { ArrowRight, Check, CircleHelp, Coins, Eye, RefreshCw, ShieldCheck } from 'lucide-react';
import { CREDIT_PACKS } from '@/lib/payments/config';
import { SectionHeading } from '@/components/finalframe/section-heading';

export default function PricingPage() {
  return <div>
    <section className="ff-section bg-[#f4ead6]"><div className="ff-container"><p className="ff-eyebrow">Credits, not confusing plans</p><h1 className="public-heading-hero mt-5 max-w-4xl">Pay for the videos you choose to make.</h1><p className="public-body-text mt-7 max-w-2xl">FinalFrame shows an estimate before generation. Buy credits when you need them, then keep any reserved credits from failed work.</p></div></section>
    <section className="ff-section"><div className="ff-container"><div className="grid gap-5 md:grid-cols-3">{CREDIT_PACKS.map((pack, index) => <article key={pack.id} className={`pricing-card ${index === 1 ? 'border-primary/70 bg-[#fff8e9] shadow-[0_25px_70px_-35px_hsl(38_86%_48%_/_0.7)]' : ''}`}><div className="flex items-center justify-between"><p className="ff-eyebrow">{pack.label}</p>{index === 1 && <span className="rounded-full bg-[#f6dfb1] px-3 py-1.5 text-xs font-semibold">Popular</span>}</div><p className="ff-display mt-8 text-4xl font-semibold">{pack.credits} <span className="text-lg tracking-normal text-muted-foreground">credits</span></p><p className="mt-3 text-sm leading-6 text-muted-foreground">A flexible starting point for short videos, experiments, and your next idea.</p><div className="mt-7 space-y-3 text-sm text-muted-foreground"><p className="flex gap-2"><Check className="mt-0.5 size-4 text-[hsl(var(--success))]" /> Use across video projects</p><p className="flex gap-2"><Check className="mt-0.5 size-4 text-[hsl(var(--success))]" /> See the estimate first</p><p className="flex gap-2"><Check className="mt-0.5 size-4 text-[hsl(var(--success))]" /> No monthly commitment</p></div><Link href="/signup" className={`mt-8 w-full ${index === 1 ? 'ff-button-primary' : 'ff-button-secondary'}`}>Start with {pack.label.toLowerCase()} <ArrowRight className="size-4" /></Link></article>)}</div><p className="mt-6 text-center text-xs text-muted-foreground">Local currency checkout is shown when you purchase. Final prices are confirmed before payment.</p></div></section>
    <section className="ff-section border-y border-border/70 bg-secondary/35"><div className="ff-container"><SectionHeading eyebrow="How the balance works" title="You are never charged for a mystery step." align="center" /><div className="mt-12 grid gap-4 md:grid-cols-4">{[[Coins,'Estimate','See the expected credit cost.'],[Eye,'Approve','Choose whether the plan is worth making.'],[RefreshCw,'Reserve','Credits are held while work runs.'],[ShieldCheck,'Release','Failed work releases its reservation.']].map(([Icon, title, description]) => <div key={title as string} className="rounded-[1.2rem] bg-background p-6"><div className="grid size-10 place-items-center rounded-xl bg-[#f6dfb1]"><Icon className="size-5" /></div><h3 className="mt-8 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description as string}</p></div>)}</div></div></section>
    <section className="ff-section"><div className="ff-container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Still wondering?" title="Start small, learn what your ideas cost." description="You do not need to buy a large pack before you know how FinalFrame fits your work." /><div className="space-y-3">{['Can I make a plan without spending credits?','Do credits expire?','What happens if a take fails?','Can my team use one balance?'].map((question) => <details key={question} className="group rounded-[1rem] border border-border/70 bg-card px-5 py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold"><span>{question}</span><CircleHelp className="size-4 text-muted-foreground transition group-open:text-accent" /></summary><p className="mt-3 text-sm leading-6 text-muted-foreground">FinalFrame will show the applicable answer in the product and checkout flow for your account and region.</p></details>)}</div></div></section>
    <section className="ff-container pb-24 sm:pb-32"><div className="rounded-[2rem] bg-foreground p-8 text-background sm:p-14"><h2 className="ff-display max-w-2xl text-4xl font-semibold sm:text-5xl">Your next video does not need a subscription to start.</h2><Link href="/signup" className="ff-button-primary mt-8">Start creating <ArrowRight className="size-4" /></Link></div></section>
  </div>;
}
